name: demo_plugin_platform_interface
description: A common platform interface for the demo_plugin plugin.
repository: https://github.com/nguyentrinh2611/demo_plugin/tree/main/demo_plugin_platform_interface
version: 1.0.0
homepage:

environment:
  sdk: ^3.5.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
